---
name: "Build docker images"

on:
  #schedule:
  #  - cron: 0 12 */7 * *
  push:
    paths:
      - '.forgejo/workflows/build-tools-docker.yml'
      - 'linux/debian/**'
    branches:
      - 'master'
      - 'runner/dind'
  pull_request:
    paths:
      - '.forgejo/workflows/build-tools-docker.yml'
      - 'tools/docker/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: "docker"
    container:
      env:
        DOCKER_CERT_PATH: "/certs/client"
        DOCKER_HOST: "tcp://docker:2376"
        DOCKER_TLS: 1
      image: "harbor.edler.cloud/docker.io/library/docker:dind"
      volumes:
        - "certs:/certs"
    services:
      docker:
        image: "harbor.edler.cloud/docker.io/library/docker:dind"
        volumes:
          - "certs:/certs"
    steps:
      #- name: Checkout
      #  uses: actions/checkout@v4

      - run: |
          set -ex
          env
          pwd
          whoami
          ls -al
          tail -f /dev/null
          docker run --rm hello-world
