---
name: "Build docker images"

on:
  #schedule:
  #  - cron: 0 12 */7 * *
  push:
    paths:
      - '.forgejo/workflows/build-tools-docker.yml'
      - 'linux/debian/**'
    branches:
      - 'master'
      - 'runner/dind'
  pull_request:
    paths:
      - '.forgejo/workflows/build-tools-docker.yml'
      - 'tools/docker/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: docker
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - run: |
          set -ex
          pwd
          whoami
          ls -al
